package org.jkiss.dbeaver.model.sourcecode.core;

public class CodeColumnAttribute {
	
	private String columnName;
	private String desciption;
	private String codeName;
	private String paramName;
	private String javaType;
	private String javaPackage;
	private Boolean isAutoGenerated;
	private Boolean isRequired;
	private Boolean isPrimary;
	private String  defaultValue;
	  
	private Boolean sqlInsertSelected;
	private Boolean sqlUpdateSelected;
	private Boolean htmlSearchSelected;
	private Boolean htmlInputFormSelected;
	private Boolean htmlTableListSelected;
	public String getColumnName() {
		return columnName;
	}
	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}
	public String getDesciption() {
		return desciption;
	}
	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}
	public String getCodeName() {
		return codeName;
	}
	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}
	public String getParamName() {
		return paramName;
	}
	public void setParamName(String paramName) {
		this.paramName = paramName;
	}
	public String getJavaType() {
		return javaType;
	}
	public void setJavaType(String javaType) {
		this.javaType = javaType;
	}
	public String getJavaPackage() {
		return javaPackage;
	}
	public void setJavaPackage(String javaPackage) {
		this.javaPackage = javaPackage;
	}
	public Boolean getIsAutoGenerated() {
		return isAutoGenerated;
	}
	public void setIsAutoGenerated(Boolean isAutoGenerated) {
		this.isAutoGenerated = isAutoGenerated;
	}
	public Boolean getIsRequired() {
		return isRequired;
	}
	public void setIsRequired(Boolean isRequired) {
		this.isRequired = isRequired;
	}
	public Boolean getIsPrimary() {
		return isPrimary;
	}
	public void setIsPrimary(Boolean isPrimary) {
		this.isPrimary = isPrimary;
	}
	public String getDefaultValue() {
		return defaultValue;
	}
	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}
	public Boolean getSqlInsertSelected() {
		return sqlInsertSelected;
	}
	public void setSqlInsertSelected(Boolean sqlInsertSelected) {
		this.sqlInsertSelected = sqlInsertSelected;
	}
	public Boolean getSqlUpdateSelected() {
		return sqlUpdateSelected;
	}
	public void setSqlUpdateSelected(Boolean sqlUpdateSelected) {
		this.sqlUpdateSelected = sqlUpdateSelected;
	}
	public Boolean getHtmlSearchSelected() {
		return htmlSearchSelected;
	}
	public void setHtmlSearchSelected(Boolean htmlSearchSelected) {
		this.htmlSearchSelected = htmlSearchSelected;
	}
	public Boolean getHtmlInputFormSelected() {
		return htmlInputFormSelected;
	}
	public void setHtmlInputFormSelected(Boolean htmlInputFormSelected) {
		this.htmlInputFormSelected = htmlInputFormSelected;
	}
	public Boolean getHtmlTableListSelected() {
		return htmlTableListSelected;
	}
	public void setHtmlTableListSelected(Boolean htmlTableListSelected) {
		this.htmlTableListSelected = htmlTableListSelected;
	}
	
	
	
	 
}
