package org.jkiss.dbeaver.model.sourcecode.core;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.sourcecode.utils.CodeHelper;
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
import org.jkiss.dbeaver.model.struct.rdb.DBSTable;
import org.jkiss.dbeaver.model.struct.rdb.DBSTableColumn;
import org.jkiss.dbeaver.model.struct.rdb.DBSTableIndex;
import org.jkiss.dbeaver.model.struct.rdb.DBSTableIndexColumn;
import org.jkiss.utils.CommonUtils;

public class SourceCodeTableAdapter {

	
	public SourceCodeTable adapterTable(DBSTable table,SourceCodeSetting setting,DBRProgressMonitor monitor) {
		
		if(table==null || setting==null)
		{
			return null;
		}
		String tableName=table.getName();
		SourceCodeTable sourceCodeTable=new SourceCodeTable();
		sourceCodeTable.setTableName(tableName);
		sourceCodeTable.setTableDesciption(CodeHelper.emptyString(table.getDescription(), false));
		sourceCodeTable.setTableNameUpperCamelCase(CodeHelper.toCamelCase(tableName));
		sourceCodeTable.setTableNameUpperCamelCase(CodeHelper.toLowerCamelCase(tableName));
		
		SourceCodeJavaClass javaEntity=fileRule2JavaClass(tableName,setting.getRuleEntity(),setting);
		SourceCodeJavaClass javaDao=fileRule2JavaClass(tableName,setting.getRuleDao(),setting);
		SourceCodeJavaClass javaComponent=fileRule2JavaClass(tableName,setting.getRuleComponent(),setting);
		SourceCodeJavaClass javaComponentImpl=fileRule2JavaClass(tableName,setting.getRuleComponentImpl(),setting);
		SourceCodeJavaClass javaService=fileRule2JavaClass(tableName,setting.getRuleService(),setting);
		SourceCodeJavaClass javaServiceImpl=fileRule2JavaClass(tableName,setting.getRuleServiceImpl(),setting);
		SourceCodeJavaClass javaController=fileRule2JavaClass(tableName,setting.getRuleController(),setting);
		SourceCodeJavaClass javaPage=fileRule2JavaClass(tableName,setting.getClassPage(),setting);
		SourceCodeJavaClass javaJsonView=fileRule2JavaClass(tableName,setting.getClassJsonView(),setting);
		SourceCodeJavaClass javaBusinessException=fileRule2JavaClass(tableName,setting.getClassBusinessException(),setting);
		SourceCodeJavaClass javaAssertUtils=fileRule2JavaClass(tableName,setting.getClassBusinessException(),setting);
		SourceCodeJavaClass javaBaseController=fileRule2JavaClass(tableName,setting.getClassBaseController(),setting);
		 
		sourceCodeTable.setJavaEntity(javaEntity);
		sourceCodeTable.setJavaDao(javaDao);
		sourceCodeTable.setJavaComponent(javaComponent);
		sourceCodeTable.setJavaComponentImpl(javaComponentImpl);
		sourceCodeTable.setJavaService(javaService);
		sourceCodeTable.setJavaServiceImpl(javaServiceImpl);
		sourceCodeTable.setJavaController(javaController);
		sourceCodeTable.setJavaPage(javaPage);
		sourceCodeTable.setJavaJsonView(javaJsonView);
		sourceCodeTable.setJavaBusinessException(javaBusinessException);
		sourceCodeTable.setJavaAssertUtils(javaAssertUtils);
		sourceCodeTable.setJavaBaseController(javaBaseController);
		
		
		// primaryKey
		SourceCodeTableColumn primaryKeyColumn=null;
		 List<SourceCodeTableColumn> columns=new ArrayList<SourceCodeTableColumn>();
		 List<SourceCodeTableColumn> tableListCols=new ArrayList<SourceCodeTableColumn>();
		 List<SourceCodeTableColumn> inputForms=new ArrayList<SourceCodeTableColumn>();
		 List<SourceCodeTableColumn> searchForms=new ArrayList<SourceCodeTableColumn>();
		try {
			 Collection<? extends DBSTableIndex> indexes = table.getIndexes(monitor);
		     if (!CommonUtils.isEmpty(indexes)) {
		         for (DBSTableIndex index : indexes) {
		        	 if( index.isPrimary())
		        	 {
		        		 List<? extends DBSTableIndexColumn>  tableColumn=index.getAttributeReferences(monitor);
		        		 for(DBSTableIndexColumn column:tableColumn)
		        		 {
		        			 DBSTableColumn primaryColumn= column.getTableColumn();
		        			 if(primaryColumn!=null)
		        			 {
			            			boolean useGeneratedKeys=primaryColumn.isAutoGenerated();
			            			 String primaryKey=primaryColumn.getName();
			            			 String primaryKey_upperCamelCase=CodeHelper.toUpperCamelCase(primaryKey);
			            			 String primaryKey_lowerCamelCase=CodeHelper.toLowerCamelCase(primaryKey);
			            			 
			            			 String mPrimaryKey_typeName=CodeHelper.columnType2JavaType(primaryColumn);
			            			 String mPrimaryKey_paramName= primaryKey_lowerCamelCase;
			            			 primaryKeyColumn=new SourceCodeTableColumn();
			            			 primaryKeyColumn.setColumnName(primaryKey);
			            			 primaryKeyColumn.setDesciption(primaryColumn.getDescription());
			            			 primaryKeyColumn.setIsAutoGenerated(useGeneratedKeys);
			            			 primaryKeyColumn.setIsPrimary(true);
			            			 primaryKeyColumn.setIsRequired(primaryColumn.isRequired());
			            			 primaryKeyColumn.setUpperCamelCaseName(primaryKey_upperCamelCase);
			            			 primaryKeyColumn.setLowerCamelCaseName(primaryKey_lowerCamelCase);
			            			 primaryKeyColumn.setJavaType(mPrimaryKey_typeName);
			            			 sourceCodeTable.setPrimaryColumn(primaryKeyColumn);
		        			 }
		        		 }
		        		 
		        	 }
		         }
		         
		     }
		
		
		
		
		 List<DBSEntityAttribute> attrs= (List<DBSEntityAttribute>)table.getAttributes(monitor);
		 if(attrs!=null)
		 {
			 for(DBSEntityAttribute attr:attrs)
			 { 
				 
				 String columnName=attr.getName();
				 String codeName=CodeHelper.toLowerCamelCase(columnName);
				 String codeName_upperCamelCase=CodeHelper.toUpperCamelCase(columnName);
				  
				  SourceCodeTableColumn codeColumn=new SourceCodeTableColumn();
				  codeColumn.setIsRequired(attr.isRequired());
				  codeColumn.setColumnName(columnName);
				  codeColumn.setDesciption(attr.getDescription());
				  codeColumn.setUpperCamelCaseName(codeName_upperCamelCase);
				  codeColumn.setLowerCamelCaseName(codeName);
				  codeColumn.setJavaType(CodeHelper.columnType2JavaType(attr));
				  codeColumn.setDefaultValue(attr.getDefaultValue());
				  
				  boolean isPrimary=false;
				  boolean isAutoGenerated=attr.isAutoGenerated();
				  if(isAutoGenerated)
				  {
					  codeColumn.setIsPrimary(true);
					  codeColumn.setIsAutoGenerated(isAutoGenerated);
				  }else {
					 if(primaryKeyColumn!=null && columnName.equals(primaryKeyColumn.getColumnName())){
						 codeColumn.setIsPrimary(true);
					 }else {
						 codeColumn.setIsPrimary(false);
					 }
				  }
				  columns.add(codeColumn);
				  
				  if(isHtmlTableColumn(codeColumn))
				  {
					  tableListCols.add(codeColumn);
				  }
				  if(isHtmlInputForms(codeColumn))
				  {
					  inputForms.add(codeColumn);
				  }
				  if(isHtmlSearchForms(codeColumn))
				  {
					  searchForms.add(codeColumn);
				  }
				 
			 }
		 }
		 
		}catch (DBException e) {
			e.printStackTrace();
		}
		sourceCodeTable.setColumns(columns);
		sourceCodeTable.setInputForms(inputForms);
		sourceCodeTable.setSearchForms(searchForms);
		sourceCodeTable.setTableListCols(tableListCols);
		 
		
		return sourceCodeTable;
		
	}
	
	private SourceCodeJavaClass fileRule2JavaClass(String tableName,String rule,SourceCodeSetting setting) {
		
		String fullName=fillRuleFullName(tableName,rule,setting);
		SourceCodeJavaClass javaClass=new SourceCodeJavaClass();
		javaClass.setName(fullName);
		javaClass.setPackageName(CodeHelper.getPackageName(fullName));
		javaClass.setSimpleName(CodeHelper.getClassSimpleName(fullName));
		javaClass.setParamName(CodeHelper.toLowerCamelCase(javaClass.getSimpleName()));
		return javaClass;
	}
	
	private boolean isHtmlTableColumn(SourceCodeTableColumn column)
	{
		if(column.getIsPrimary())
		{
			return false;
		}
		return true;
	}
	private boolean isHtmlInputForms(SourceCodeTableColumn column)
	{
		if(column.getIsPrimary())
		{
			return false;
		}
		return true;
	}
	private boolean isHtmlSearchForms(SourceCodeTableColumn column)
	{
		if(column.getIsPrimary())
		{
			return false;
		}
		return true;
	}
	
	public String fillRuleFullName(String tableName,String rule,SourceCodeSetting setting)
	{
		if(CodeHelper.isEmpty(rule))
		{
			return tableName;
		}
		Map<String, Object> params=new HashMap<String, Object>();
		params.put("package_name", setting.getPackagePath());
		params.put("group_name", setting.getGroupName());
		params.put("table_name", tableName);
		return CodeHelper.processTemplate(rule, params);
	}
}
